<a href="https://colab.research.google.com/github/vyom10445/tensorflow/blob/main/tensorflow_basics_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.20.0


In [3]:
#create tensor with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
#check no. of dimensions of tensor
scalar.ndim

0

In [5]:
#create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
#check dimesion of verctor
vector.ndim

1

In [7]:
#create a matrix (has more than 1 dimn)
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
#create another matrix
another_matrix= tf.constant([[10.,7.],
                             [3.,2.],
                             [8.,9.]] , dtype=tf.float16) #specify the datatype with

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
another_matrix.ndim

2

In [11]:
#lets create a tensor
tensor =tf.constant([[[1,2,3,],
                      [4,5,6]],
                     [[7,8,9],
                      [10,11,12]],
                     [[13,14,15],
                      [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
tensor.ndim

3

In [13]:
#creating tensors with variable
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor= tf.constant([10,7])

In [14]:
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [15]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [16]:
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [17]:
#creating random tensors
#in notes give example of nn first initialises with random weights then sees examples and updates representation outputs and tweak its random value acc to examples and then repeat with more examples
#creating 2random (but the same) tensors

random_1= tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1=random_1.normal(shape=(3,2))
random_2= tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))

#Are they equal?
random_1,random_2 , random_1==random_2
#not exactly random but pseudorandom cos they have seeds

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [18]:
#shuffle a tensor (valuable when you want to shuffle your data so the inherent learning is not affected)
#in notes give example like if there was food image classification neural networkand we had 15k imgs of sphaghetti , 10k of ramen , then nn will see sphagetti first and then its pattern will be too alligned to spahaghetti img than to a ramen img
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
#shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)
#shuffles it along its 1st dimension which means 3 , not 2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [19]:
#it looks like if we want out shuffled tensors to be in the same order , we' ve got to use the global lvl random seed and operational level random seed
tf.random.set_seed(42) #global lvl random seed
tf.random.shuffle(not_shuffled, seed=42)#oprtnl lvl random seed , if used alone , will get different results each time

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [20]:
#other ways to make tensors
#create tensor of all ones
tf.ones([4,3])
#create tensor of all zeros
tf.zeros([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [21]:
#you can also turn numpy arrays into tensoflow tensors
#the main difference bw numpy array and tensorflow tensor is that tensors can be run on a GPU(much faster for numerical computing)
import numpy as np

numpy_A= np.arange(1,25, dtype=np.int32)
numpy_A


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [22]:
A=tf.constant(numpy_A , shape=(2,3,4) ) #product must be equal to no of elements
B=tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [23]:
#getting information from tensors
#shape , rank , axis or dimn , size

#creating a rank 4 tensor (4 dimensions)
rank4_tensor= tf.zeros(shape=[2,3,4,5])
rank4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [24]:
rank4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [25]:
rank4_tensor.shape , rank4_tensor.ndim , tf.size(rank4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [26]:
#get various attributes of our tensor
print("Datatype of every element:", rank4_tensor.dtype)
print("Number of dimensions (rank):", rank4_tensor.ndim)
print("Shape of tensor:", rank4_tensor.shape)
print("Elements along the 0 axis:", rank4_tensor.shape[0])
print("Elements along the last axis:", rank4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank4_tensor))
print("Total number of elements in our tensor:", tf.size(rank4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120


In [27]:
# indexing tensors
#tensors can be indexed just like python lists
some_list= [1,2,3,4]
some_list[:2]

#get the first 2 elements of each dimension
rank4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [28]:
#get 1st element from each dimension from each index except for the final one
rank4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [29]:
#create a rank 2 tensor
rank2_tensor=tf.constant([[10,7],
                          [3,4]])
rank2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [30]:
#get last item of each row
rank2_tensor[:,-1]  #get every row , last column

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [31]:
#add in extra dimension to our rank 2 tensor
rank3_tensor = rank2_tensor[..., tf.newaxis] #... means :,: (every access beforr that)
rank3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [32]:
#alternate to tf.newaxis
tf.expand_dims(rank2_tensor, axis=-1) #'-1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [33]:
tf.expand_dims(rank2_tensor , axis=0) #expand the 0 axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [34]:
tf.expand_dims(rank2_tensor, axis=1) #expand the 1 axis

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

In [35]:
#manipulating tensors
#u can add values to a tensor using addn operator
tensor = tf.constant([[10,7],
                      [3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [36]:
#original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [37]:
#multiplication also works

In [38]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [39]:
#subtraction works too

In [40]:
#we can use tensorflow built-in funcn too
tf.multiply(tensor , 10) #better on gpu

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [42]:
#MATRIX MULTLIPICATION

print(tensor)
tf.linalg.matmul(tensor , tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [43]:
#matrix multiplication with python operator "@"
tensor@tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [54]:
X=tf.constant([[1,2],
               [3,4],
               [5,6]])
Y=tf.constant([[7,8],
               [9,10],
               [11,12]])
X,Y
#multiplation wont be possible to since 3,2 and 3,2 not possible since innter dimensions must match

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [58]:
#there r 2 ways to change shape 1.reshape 2.transpose

tf.reshape (X, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [59]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [60]:
#so 2 different resulkts by both , now lets see multn results
tf.matmul(X, tf.reshape(Y , shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [61]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [63]:
#changing data types
B = tf.constant([1.2 , 6.7])
B.dtype

tf.float32

In [64]:
C= tf.constant([3,4])
C.dtype

tf.int32

In [66]:
#change from float32 to float16 (reduced precision)
D= tf.cast(B , dtype= tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.2, 6.7], dtype=float16)>

In [68]:
#changing from int32 to float32
E= tf.cast(C , dtype = tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 4.], dtype=float32)>